FROM python:3.4.2

LABEL maintainer="Just van den Broecke <justb4@gmail.com>"

#
# ARGS
#
ARG TIMEZONE="Europe/Amsterdam"
ARG LOCALE="en_US.UTF-8"

ARG ADD_PYTHON_DEB_PACKAGES="python3-numpy"
ARG ADD_PYTHON_PIP_PACKAGES="pip==18.1 numpy"

#
# ENV settings
#
ENV TZ=${TIMEZONE} \
   LC_ALL="${LOCALE}" \
   LC_TYPE="${LOCALE}" \
   LANG="${LOCALE}" \
   LANGUAGE="${LOCALE}" \
   DEBIAN_FRONTEND="noninteractive" \
   BUILD_DEPS="tzdata locales" \
   PYTHON_CORE_PACKAGES="cython3 python3-requests python3-tz python3-pandas python3-setuptools python3-lxml python3-gdal python3-psycopg2 python3-jinja2 gdal-bin libgdal-dev" \
   PYTHON_EXTRA_DEB_PACKAGES="${ADD_PYTHON_DEB_PACKAGES}"  \
   PYTHON_EXTRA_PIP_PACKAGES="${ADD_PYTHON_PIP_PACKAGES}" \
   PYTHONPATH="/stetl" \
   CPLUS_INCLUDE_PATH="/usr/include/gdal" \
   C_INCLUDE_PATH="/usr/include/gdal"


# Add Source Code
COPY . /stetl
VOLUME /stetl

# Set time right and configure timezone and locale
RUN \
    # Timezone
    echo "${TZ}" > /etc/timezone \
    && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
    && apt-get update \
    && apt-get --no-install-recommends install  -y \
        ${BUILD_DEPS} \
        ${PYTHON_CORE_PACKAGES} \
        ${PYTHON_EXTRA_DEB_PACKAGES} \
    && echo "LANG=${LANG}" >/etc/default/locale  \
    && echo "${LANG} UTF-8" > /etc/locale.gen \
    && locale-gen \
    && dpkg-reconfigure locales \
    && /usr/sbin/update-locale LANG=${LANG} \
    && dpkg-reconfigure tzdata \
    # Optional packages to install via Pip
    && if [ "x${PYTHON_EXTRA_PIP_PACKAGES}" = "x" ] ;\
        then \
            echo "No extra Pip packages to install" ;\
        else \
            pip install ${PYTHON_EXTRA_PIP_PACKAGES} ;\
        fi

RUN \
    cd /stetl \
    && pip install -r requirements-main.txt \
    && pip install -r requirements-dev.txt

#     # Install and Remove build-related packages for smaller image size
#     cd /stetl \
#         && python setup.py install  \
#         && apt autoremove -y  \
#         && rm -rf /var/lib/apt/lists/* \
#         
#     && echo "For ${TZ} date=`date`" \
#     && echo "locale=`locale`"


# Build dockerfile with
# docker build . -t stetl_python3_dev -f Dockerfile_py3
# Start developing with
# docker run -it --rm -v $(PWD):/stetl stetl_python3_dev /bin/bash
